In [1]:
import torch
import torch.nn.functional as F

In [2]:
z = torch.FloatTensor([1,2,3])

In [3]:
# 소프트 맥스 함수
hypothesis = F.softmax(z, dim = 0)
hypothesis

tensor([0.0900, 0.2447, 0.6652])

In [4]:
import numpy as np
np.exp(1.0)/(np.exp(1.0)+np.exp(2.0)+np.exp(3.0))

0.09003057317038046

In [5]:
np.exp(2.0)/(np.exp(1.0)+np.exp(2.0)+np.exp(3.0))

0.24472847105479767

In [6]:
np.exp(3.0)/(np.exp(1.0)+np.exp(2.0)+np.exp(3.0))

0.6652409557748219

In [7]:
hypothesis.sum() # 히든 레이어에 무슨 과정이 있든 output의 합은 1이다.

tensor(1.)

In [8]:
# MNIST 손글씨
!pip install torchvision

In [9]:
import torch
import torch.nn as nn
import torchvision.datasets as dsets
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
import random
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [10]:
# MNIST 자료 다운
mnist_train = dsets.MNIST(root='MNIST_data/',
                         train = True,
                         transform = transforms.ToTensor(),
                         download=True)

mnist_test = dsets.MNIST(root='MNIST_data/',
                         train = False,
                         transform = transforms.ToTensor(),
                         download=True)

training_epochs = 15
batch_size = 100
data_loader = torch.utils.data.DataLoader(dataset=mnist_train,
                                         batch_size=batch_size,
                                         shuffle=True, drop_last=True)

C:\ProgramData\Anaconda3\lib\site-packages\torchvision\datasets\mnist.py:498: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:180.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)


In [11]:
mnist_train[0]

(tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 

In [12]:
image,label = mnist_train[0]
print(image.shape, label) # 맨앞 1 = 흑백 / 5에 그림이다.

torch.Size([1, 28, 28]) 5


In [13]:
image,label = mnist_train[4]
print(image.shape, label) # 맨앞 1 = 흑백 / 9에 그림이다.

torch.Size([1, 28, 28]) 9


In [14]:
import matplotlib.pyplot as plt
import numpy as np
# plt.imshow(image.reshape(28, 28), cmap='gray')
# img = np.reshape(image, [28, 28])
# plt.imshow(img, cmap='Greys')

In [15]:
linear = nn.Linear(28*28, 10, bias = True)

In [16]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.1)

In [17]:
for epoch in range(training_epochs):
    avg_cost = 0
    total_batch = len(data_loader)
    
    for X, y in data_loader:
        X = X.view(-1, 28*28)
        y = y
        
        hypothesis = linear(X)
        cost = criterion(hypothesis, y)
        optimizer.zero_grad()
        cost.backward()
        optimizer.step()
        
        avg_cost += cost/total_batch
    print('Epoch:', '%04d' %(epoch+1), 'cost=', "{:.9f}".format(avg_cost))
        

Epoch: 0001 cost= 0.533881009
Epoch: 0002 cost= 0.359130800
Epoch: 0003 cost= 0.331026435
Epoch: 0004 cost= 0.316200465
Epoch: 0005 cost= 0.306965530
Epoch: 0006 cost= 0.300246567
Epoch: 0007 cost= 0.294970453
Epoch: 0008 cost= 0.290832430
Epoch: 0009 cost= 0.287257314
Epoch: 0010 cost= 0.284187764
Epoch: 0011 cost= 0.281961352
Epoch: 0012 cost= 0.279427111
Epoch: 0013 cost= 0.277855515
Epoch: 0014 cost= 0.275954545
Epoch: 0015 cost= 0.274450421


In [19]:
with torch.no_grad():
    X_test = mnist_test.test_data.view(-1, 28*28).float()
    y_test = mnist_test.test_labels
    
    prediction = linear(X_test)
    
    correct_prediction = torch.argmax(prediction, 1) == y_test
    accuracy = correct_prediction.float().mean()
    print('acc:', accuracy.item())
    r = random.randint(0, len(mnist_test)-1)
    X_single_data = mnist_test.test_data[r:r+1].view(-1, 28*28).float()
    y_single_data = mnist_test.test_labels[r:r+1]
    print('Label:', y_single_data.item())
    single_prediction = linear(X_single_data)
    print('Prediction:', torch.argmax(single_prediction, 1).item())
    
#     plt.imshow(mnist_test.test_data[r:r+1].view(28,28), cmap="Grays",
#               interpolation='nearest');

acc: 0.8845000267028809
Label: 3
Prediction: 3


In [20]:
# Neural Network - Deep learning

In [21]:
# layering
## nn.Linear(784, 10) 784 -> 10
### 784 => 256 => 256 => 10
linear1 = nn.Linear(784, 256, bias=True)
linear2 = nn.Linear(256, 256, bias=True)
linear3 = nn.Linear(256, 10, bias=True)
relu = torch.nn.ReLU()

In [23]:
nn.init.normal_(linear1.weight)
nn.init.normal_(linear2.weight)
nn.init.normal_(linear3.weight)

Parameter containing:
tensor([[ 1.6893, -0.4671,  0.5253,  ..., -0.0257,  0.2940, -0.2990],
        [-0.5818, -2.3138, -0.1847,  ..., -0.2662, -0.1162, -0.2116],
        [-0.2966, -0.4684, -1.8893,  ..., -1.2298,  0.5110,  1.5660],
        ...,
        [ 1.6858, -1.0401,  0.3106,  ...,  0.9472, -0.4404, -0.1522],
        [-0.8159,  0.7047,  0.4257,  ..., -0.5285,  0.8930,  0.0655],
        [ 1.8216,  0.3508, -0.6248,  ...,  0.0724, -0.5328,  1.1339]],
       requires_grad=True)

In [25]:
model = nn.Sequential(linear1,relu, linear2, relu, linear3)

In [31]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr = 0.001)
total_batch = len(data_loader)
train_epochs = 15
batch_size = 100

for epoch in range(train_epochs):
    avg_cost = 0
    for X, y in data_loader:
        X = X.view(-1, 28*28)
        y = y
        optimizer.zero_grad()
        hyp = model(X)
        cost = criterion(hyp, y)
        cost.backward()
        optimizer.step()
        avg_cost+=cost/total_batch
    print('Epoch:', "%04d"%(epoch+1), 'cost=', '{:0.9f}'.format(avg_cost))
print("End")

Epoch: 0001 cost= 0.722817540
Epoch: 0002 cost= 0.517449379
Epoch: 0003 cost= 0.412883133
Epoch: 0004 cost= 0.416101992
Epoch: 0005 cost= 0.379029304
Epoch: 0006 cost= 0.326235890
Epoch: 0007 cost= 0.290790617
Epoch: 0008 cost= 0.272243381
Epoch: 0009 cost= 0.322498947
Epoch: 0010 cost= 0.284422606
Epoch: 0011 cost= 0.187442034
Epoch: 0012 cost= 0.282492965
Epoch: 0013 cost= 0.272864014
Epoch: 0014 cost= 0.197593585
Epoch: 0015 cost= 0.147219941
End


In [30]:
with torch.no_grad():
    X_test = mnist_test.test_data.view(-1, 28*28).float()
    y_test = mnist_test.test_labels
    
    prediction = linear(X_test)
    
    correct_prediction = torch.argmax(prediction, 1) == y_test
    accuracy = correct_prediction.float().mean()
    print('acc:', accuracy.item())
    r = random.randint(0, len(mnist_test)-1)
    X_single_data = mnist_test.test_data[r:r+1].view(-1, 28*28).float()
    y_single_data = mnist_test.test_labels[r:r+1]
    print('Label:', y_single_data.item())
    single_prediction = linear(X_single_data)
    print('Prediction:', torch.argmax(single_prediction, 1).item())
    
#     plt.imshow(mnist_test.test_data[r:r+1].view(28,28), cmap="Grays",
#               interpolation='nearest');

acc: 0.8845000267028809
Label: 7
Prediction: 7
